### ISSUE TITLE
Plugin Parameters shows nothing after Save & New (Joomla 4)

### ISSUE THREAD

**Issue by DSist** [widgetfactory/jce#105]
**Describe the bug**
Plugin Parameters shows nothing after Save & New

**To Reproduce**

1. Go to 'Profiles - Default - Plugin Parameters - Style Select'
2. Click on 'Save & New'
3. Click on Plugin Parameters tab again
4. Empty screen

**Expected behavior**
Plugin Parameters tab page

**Additional context**
Clean Joomla 4.0.5 installation
Maintenance: Global Check-in shows 'xxxxx_wf_profiles'

**Comment by ryandemmer** [comment]
No items are shown in the Plugin Parameters tab because when you create a new profile, either using the New button or the Save & New button, you are creating an empty editor, with no buttons.

Once you assign buttons in the Features & Layout tab, the corresponsing parameter fields will be displayed in the Plugin Parameters tab.

**Comment by DSist** [comment]
Got it. Thank you!
