### ISSUE TITLE
 JCE Pro 2.8.5  PRO - Remove Image EXIF option is enabled, an error occurred after uploading 

### ISSUE THREAD

**Issue by redakcjaSP11** [widgetfactory/jce#70]
When the Remove Image EXIF ​​option is enabled, an error occurred after uploading the last update.
![Zrzut ekranu (14)](https://user-images.githubusercontent.com/60510027/73540735-ff443300-4430-11ea-9a37-2617b1fe5bd2.png)

Upload failed: Exif data could not be removed from this image.

![Zrzut ekranu (15)](https://user-images.githubusercontent.com/60510027/73540745-0408e700-4431-11ea-8b79-6231c64afaa7.png)

The picture is not uploaded.
Disabling this feature allows you to upload a photo, but I'd prefer this feature to work

**Comment by ryandemmer** [comment]
This has been fixed in the current beta - https://www.joomlacontenteditor.net/downloads/editor/pro/development

Also, if you are using the PHP GD2 library for resizing (this error indicates that you are), EXIF data is removed from images that are resized on upload, whether the Remove EXIF option is set or not.
